services:
  db:
    image: pgvector/pgvector:pg18
    container_name: ragitect_db
    environment:
      POSTGRES_DB: ragitect_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
