[project]
name = "ragitect"
version = "0.1.0"
description = "Ragitect"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.5",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.0",
    "langchain-openai>=1.0.2",
    "python-dotenv>=1.2.1",
    "streamlit>=1.51.0",
]

[dependency-groups]
dev = [
    "faiss-cpu>=1.12.0",
    "langchain-text-splitters>=1.0.0",
    "openai>=2.7.2",
]
