[project]
name = "ragitect"
version = "0.1.0"
description = "Ragitect"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.9.0",
    "docling>=2.61.2",
    "langchain-community>=0.3.17",
    "langchain-litellm>=0.3.0",
    "litellm>=1.79.3",
    "pypdf>=6.2.0",
    "python-dotenv>=1.2.1",
    "streamlit>=1.51.0",
]

[dependency-groups]
dev = [
    "faiss-cpu>=1.12.0",
    "langchain-ollama>=0.3.10",
    "openai>=2.7.2",
]
